"""add category in product

Revision ID: 332492d81352
Revises: ac2985df908e
Create Date: 2025-10-04 01:27:18.122091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332492d81352'
down_revision = 'ac2985df908e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
