"""edit orders

Revision ID: 90ed1619705b
Revises: 
Create Date: 2025-10-04 10:10:34.434491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90ed1619705b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('total_quantity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.create_foreign_key('fk_orders_customer_id', 'users', ['customer_id'], ['id'])
        batch_op.drop_column('total_price')
        batch_op.drop_column('customer_phone')
        batch_op.drop_column('product_name')
        batch_op.drop_column('quantity')
        batch_op.drop_column('order_method')
        batch_op.drop_column('unit_price')
        batch_op.drop_column('customer_name')
    # ### end Alembic commands ###


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('unit_price', sa.NUMERIC(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('order_method', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('product_name', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('customer_phone', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('total_price', sa.NUMERIC(precision=10, scale=2), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('payment_method')
        batch_op.drop_column('total_quantity')
        batch_op.drop_column('total_amount')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
