"""Add retailer_avatar and customer_avatar columns

Revision ID: b527c97cc9af
Revises: 30c5c14195ec
Create Date: 2025-10-03 23:10:05.333283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b527c97cc9af'
down_revision = '30c5c14195ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quick_replies')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retailer_avatar', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('customer_id', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('customer_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('customer_avatar', sa.String(length=10), nullable=True))
        batch_op.alter_column('retailer_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('retailer_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('business_name')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('avatar')
        batch_op.drop_column('last_order')
        batch_op.drop_column('priority')
        batch_op.drop_column('status')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('sender_type', sa.String(length=20), nullable=False))
        batch_op.alter_column('message_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_column('sender')
        batch_op.drop_column('attachment_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('sender', sa.VARCHAR(length=50), nullable=False))
        batch_op.alter_column('message_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('sender_type')
        batch_op.drop_column('sender_id')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_order', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('business_name', sa.VARCHAR(length=255), nullable=False))
        batch_op.alter_column('retailer_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('retailer_id',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('customer_avatar')
        batch_op.drop_column('customer_name')
        batch_op.drop_column('customer_id')
        batch_op.drop_column('retailer_avatar')

    op.create_table('quick_replies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('used_count', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
