"""Add M-Pesa fields to orders table

Revision ID: c9484859c808
Revises: 90ed1619705b
Create Date: 2025-10-04 10:31:45.131176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9484859c808'
down_revision = '90ed1619705b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpesa_phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('mpesa_checkout_request_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mpesa_merchant_request_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mpesa_response_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('mpesa_result_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('mpesa_result_desc', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('mpesa_result_desc')
        batch_op.drop_column('mpesa_result_code')
        batch_op.drop_column('mpesa_response_code')
        batch_op.drop_column('mpesa_merchant_request_id')
        batch_op.drop_column('mpesa_checkout_request_id')
        batch_op.drop_column('mpesa_phone_number')

    # ### end Alembic commands ###
